Repository MountainDash/nonebot-plugin-send-anything-anywhere, pull requests merged in 2023-08, with the labels that each got.

#63 在 TargetOB12Unknow 中加入 platform 字段
  nonebot_plugin_saa/adapters/onebot_v12.py
  nonebot_plugin_saa/adapters/qqguild.py
  nonebot_plugin_saa/utils/platform_send_target.py
  tests/test_aggreated_send.py
  tests/test_onebot_v12.py
  tests/utils.py
Labels: enhancement

#66 适配飞书
  nonebot_plugin_saa/__init__.py
  nonebot_plugin_saa/adapters/__init__.py
  nonebot_plugin_saa/adapters/feishu.py
  nonebot_plugin_saa/utils/__init__.py
  nonebot_plugin_saa/utils/const.py
  nonebot_plugin_saa/utils/platform_send_target.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_feishu.py
Labels: feature

#67 :art: Use re-export format
  nonebot_plugin_saa/__init__.py
  nonebot_plugin_saa/types/__init__.py
  nonebot_plugin_saa/utils/__init__.py
Labels: skip-changelog

#68 update metadata & README
  README.md
  nonebot_plugin_saa/__init__.py
Labels: skip-changelog

#72 添加通过 Bot 唯一标识符选择 Bot 的功能
  nonebot_plugin_saa/adapters/feishu.py
  nonebot_plugin_saa/adapters/kaiheila.py
  nonebot_plugin_saa/adapters/onebot_v11.py
  nonebot_plugin_saa/adapters/onebot_v12.py
  nonebot_plugin_saa/adapters/qqguild.py
  nonebot_plugin_saa/adapters/telegram.py
  nonebot_plugin_saa/utils/__init__.py
  nonebot_plugin_saa/utils/auto_select_bot.py
  tests/test_auto_select_bot.py
Labels: feature

#77 Revert "添加通过 Bot 唯一标识符选择 Bot 的功能"
  nonebot_plugin_saa/adapters/feishu.py
  nonebot_plugin_saa/adapters/kaiheila.py
  nonebot_plugin_saa/adapters/onebot_v11.py
  nonebot_plugin_saa/adapters/onebot_v12.py
  nonebot_plugin_saa/adapters/qqguild.py
  nonebot_plugin_saa/adapters/telegram.py
  nonebot_plugin_saa/utils/__init__.py
  nonebot_plugin_saa/utils/auto_select_bot.py
  tests/test_auto_select_bot.py
Labels: skip-changelog

#71 增添 message_receipt
  nonebot_plugin_saa/adapters/kaiheila.py
  nonebot_plugin_saa/adapters/onebot_v11.py
  nonebot_plugin_saa/adapters/onebot_v12.py
  nonebot_plugin_saa/adapters/qqguild.py
  nonebot_plugin_saa/utils/__init__.py
  nonebot_plugin_saa/utils/helpers.py
  nonebot_plugin_saa/utils/platform_send_target.py
  nonebot_plugin_saa/utils/receipt.py
  nonebot_plugin_saa/utils/types.py
  tests/test_aggreated_send.py
  tests/test_auto_select_bot.py
  tests/test_kaiheila.py
  tests/test_message_segment_build.py
  tests/test_onebot_v11.py
  tests/test_onebot_v12.py
  tests/test_qqguild.py
  tests/test_receipt.py
  tests/test_send.py
Labels: feature
