Repository MountainDash/nonebot-plugin-send-anything-anywhere, pull requests merged in 2023-11, with the labels that each got.

#116 支持选择特定 Bot 的 PlatformTarget
  nonebot_plugin_saa/auto_select_bot.py
  nonebot_plugin_saa/registries/__init__.py
  nonebot_plugin_saa/registries/platform_send_target.py
Labels: feature

#114 适配 DoDo
  .gitignore
  README.md
  nonebot_plugin_saa/__init__.py
  nonebot_plugin_saa/adapters/__init__.py
  nonebot_plugin_saa/adapters/dodo.py
  nonebot_plugin_saa/registries/__init__.py
  nonebot_plugin_saa/registries/platform_send_target.py
  nonebot_plugin_saa/utils/const.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_dodo.py
  tests/test_kaiheila.py
  tests/utils.py
Labels: feature

#115 捕获 auto select bot 功能中的各处异常
  nonebot_plugin_saa/adapters/onebot_v11.py
  nonebot_plugin_saa/adapters/red.py
  nonebot_plugin_saa/auto_select_bot.py
  tests/test_auto_select_bot.py
  tests/test_onebot_v11.py
  tests/test_red.py
Labels: bug

#119 引入 QQ群 和 QQ私聊 的 openid target
  nonebot_plugin_saa/registries/platform_send_target.py
  nonebot_plugin_saa/utils/const.py
Labels: feature

#123 导出 OpenID Target
  nonebot_plugin_saa/__init__.py
  nonebot_plugin_saa/registries/__init__.py
Labels: enhancement
