Repository MountainDash/nonebot-plugin-send-anything-anywhere, pull requests merged in 2023-03, with the labels that each got.

#22 :technologist: add ruff
  .pre-commit-config.yaml
  nonebot_plugin_saa/__init__.py
  nonebot_plugin_saa/adapters/__init__.py
  nonebot_plugin_saa/adapters/qqguild.py
  nonebot_plugin_saa/types/custom_message_segment.py
  poetry.lock
  pyproject.toml
  tests/test_message_segment_build.py
Labels: skip-changelog

#20 为Readme中的支持情况添加更直观的表格与emoji
  README.md
Labels: documentation

#23 增加 overwrite 方法
  nonebot_plugin_saa/__init__.py
  nonebot_plugin_saa/types/common_message_segment.py
  nonebot_plugin_saa/types/custom_message_segment.py
  nonebot_plugin_saa/utils/__init__.py
  nonebot_plugin_saa/utils/types.py
  tests/test_custom_message_segment.py
Labels: feature

#24 引入 SendTarget
  nonebot_plugin_saa/adapters/onebot_v11.py
  nonebot_plugin_saa/adapters/onebot_v12.py
  nonebot_plugin_saa/adapters/qqguild.py
  nonebot_plugin_saa/utils/__init__.py
  nonebot_plugin_saa/utils/send_target.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_send_target.py
Labels: feature

#25 添加从 event 中提取 send target 的方法
  nonebot_plugin_saa/__init__.py
  nonebot_plugin_saa/adapters/onebot_v11.py
  nonebot_plugin_saa/adapters/onebot_v12.py
  nonebot_plugin_saa/adapters/qqguild.py
  nonebot_plugin_saa/utils/__init__.py
  nonebot_plugin_saa/utils/send_target.py
  tests/test_send_target.py
Labels: feature

#28 :construction_worker: switch poetry installer
  .github/actions/setup-python/action.yml
Labels: skip-changelog

#29 :construction_worker: lock poetry to 1.3.2
  .github/actions/setup-python/action.yml
Labels: skip-changelog

#27 使用 PlatformTarget 代替 SendTarget
  README.md
  nonebot_plugin_saa/__init__.py
  nonebot_plugin_saa/adapters/onebot_v11.py
  nonebot_plugin_saa/adapters/onebot_v12.py
  nonebot_plugin_saa/adapters/qqguild.py
  nonebot_plugin_saa/types/__init__.py
  nonebot_plugin_saa/utils/__init__.py
  nonebot_plugin_saa/utils/const.py
  nonebot_plugin_saa/utils/platform_send_target.py
  nonebot_plugin_saa/utils/registry.py
  nonebot_plugin_saa/utils/types.py
  tests/conftest.py
  tests/test_onebot_v11.py
  tests/test_onebot_v12.py
  tests/test_platform_target.py
  tests/test_qqguild.py
Labels: Breaking

#33 修复未安装onebot适配器或qqguild适配器时导入报错的问题
  nonebot_plugin_saa/adapters/onebot_v12.py
  nonebot_plugin_saa/adapters/qqguild.py
Labels: bug

#35 支持反序列化字典
  nonebot_plugin_saa/utils/platform_send_target.py
  tests/test_platform_target.py
Labels: feature

#42 添加反序列化带 PlatformTarget 的 pydantic 对象的支持
  nonebot_plugin_saa/utils/__init__.py
  nonebot_plugin_saa/utils/platform_send_target.py
  tests/test_platform_target.py
Labels: feature
