Repository MountainDash/nonebot-plugin-send-anything-anywhere, pull requests merged in 2023-10, with the labels that each got.

#89 修复 Red 适配器撤回私聊报错的问题
  nonebot_plugin_saa/adapters/red.py
  tests/test_red.py
Labels: bug

#88 不再限制 Red 适配器的最高版本
  poetry.lock
  pyproject.toml
  tests/test_red.py
Labels: dependencies

#87 :memo: 补充 enable_auto_select_bot 的说明
  docs/docs/usage/03-send.md
  nonebot_plugin_saa/utils/auto_select_bot.py
  nonebot_plugin_saa/utils/types.py
Labels: documentation

#92 移除 metadata 中的 qqguild
  nonebot_plugin_saa/__init__.py
Labels: bug

#91 :recycle: refactor code
  nonebot_plugin_saa/__init__.py
  nonebot_plugin_saa/abstract_factories.py
  nonebot_plugin_saa/adapters/feishu.py
  nonebot_plugin_saa/adapters/kaiheila.py
  nonebot_plugin_saa/adapters/onebot_v11.py
  nonebot_plugin_saa/adapters/onebot_v12.py
  nonebot_plugin_saa/adapters/qqguild.py
  nonebot_plugin_saa/adapters/red.py
  nonebot_plugin_saa/adapters/telegram.py
  nonebot_plugin_saa/auto_select_bot.py
  nonebot_plugin_saa/registries/__init__.py
  nonebot_plugin_saa/registries/platform_send_target.py
  nonebot_plugin_saa/registries/receipt.py
  nonebot_plugin_saa/types/common_message_segment.py
  nonebot_plugin_saa/types/custom_message_segment.py
  nonebot_plugin_saa/utils/__init__.py
  tests/conftest.py
  tests/test_aggreated_send.py
  tests/test_auto_select_bot.py
  tests/test_kaiheila.py
  tests/test_message_segment_build.py
  tests/test_onebot_v11.py
  tests/test_onebot_v12.py
  tests/test_platform_target.py
  tests/test_qqguild.py
  tests/test_receipt.py
  tests/test_red.py
  tests/utils.py
Labels: skip-changelog

#93 :recycle: refactor registries
  nonebot_plugin_saa/registries/meta.py
  nonebot_plugin_saa/registries/platform_send_target.py
  nonebot_plugin_saa/registries/receipt.py
  tests/conftest.py
Labels: skip-changelog

#95 :bug: fix init_subclass error
  nonebot_plugin_saa/registries/meta.py
Labels: skip-changelog

#98 更新 adapter 适配指南
  docs/docs/dev/02-adapter.md
Labels: documentation

#97 重构 Reply
  nonebot_plugin_saa/adapters/feishu.py
  nonebot_plugin_saa/adapters/kaiheila.py
  nonebot_plugin_saa/adapters/onebot_v11.py
  nonebot_plugin_saa/adapters/onebot_v12.py
  nonebot_plugin_saa/adapters/qqguild.py
  nonebot_plugin_saa/adapters/red.py
  nonebot_plugin_saa/adapters/telegram.py
  nonebot_plugin_saa/registries/__init__.py
  nonebot_plugin_saa/registries/message_id.py
  nonebot_plugin_saa/types/common_message_segment.py
  tests/test_feishu.py
  tests/test_kaiheila.py
  tests/test_onebot_v11.py
  tests/test_onebot_v12.py
  tests/test_red.py
  tests/test_telegram.py
Labels: Breaking

#104 修复文档错误
  README.md
Labels: documentation

#101 为 auto select bot 加入更多日志信息
  nonebot_plugin_saa/auto_select_bot.py
Labels: feature

#110 修复文档错误
  docs/docs/dev/02-adapter.md
Labels: documentation
