Repository MountainDash/nonebot-plugin-send-anything-anywhere, pull requests merged in 2023-09, with the labels that each got.

#81 impl `TelegramReceipt`
  .gitignore
  nonebot_plugin_saa/adapters/telegram.py
  tests/test_telegram.py
Labels: skip-changelog

#80 feishu receipt
  nonebot_plugin_saa/adapters/feishu.py
  tests/test_feishu.py
Labels: skip-changelog

#76 适配 Red
  .gitignore
  README.md
  nonebot_plugin_saa/__init__.py
  nonebot_plugin_saa/adapters/__init__.py
  nonebot_plugin_saa/adapters/red.py
  nonebot_plugin_saa/utils/const.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_red.py
  tests/utils.py
Labels: feature

#83 增加 SaaTarget nb 依赖项
  nonebot_plugin_saa/__init__.py
  nonebot_plugin_saa/utils/__init__.py
  nonebot_plugin_saa/utils/platform_send_target.py
Labels: feature

#85 Red 适配 Receipt 与合并转发
  nonebot_plugin_saa/adapters/red.py
  poetry.lock
  pyproject.toml
  tests/test_red.py
  tests/utils.py
Labels: enhancement
