Repository MountainDash/nonebot-plugin-send-anything-anywhere, pull requests merged in 2024-01, with the labels that each got.

#129 将 Reply 的 data 字段统一为 dict
  nonebot_plugin_saa/adapters/dodo.py
  nonebot_plugin_saa/adapters/feishu.py
  nonebot_plugin_saa/adapters/kaiheila.py
  nonebot_plugin_saa/adapters/onebot_v11.py
  nonebot_plugin_saa/adapters/onebot_v12.py
  nonebot_plugin_saa/adapters/qq.py
  nonebot_plugin_saa/adapters/qqguild.py
  nonebot_plugin_saa/adapters/red.py
  nonebot_plugin_saa/adapters/telegram.py
  nonebot_plugin_saa/registries/message_id.py
  nonebot_plugin_saa/types/common_message_segment.py
  tests/test_message.py
Labels: Breaking

#131 引入config，并为QQ频道添加 magic_msg_id 相关配置
  nonebot_plugin_saa/adapters/qq.py
  nonebot_plugin_saa/adapters/qqguild.py
  nonebot_plugin_saa/config.py
  tests/test_aggreated_send.py
  tests/test_auto_select_qqguild_bot.py
  tests/test_dodo.py
  tests/test_feishu.py
  tests/test_kaiheila.py
  tests/test_message.py
  tests/test_message_segment_build.py
  tests/test_onebot_v11.py
  tests/test_onebot_v12.py
  tests/test_platform_target.py
  tests/test_qq.py
  tests/test_qqguild.py
  tests/test_red.py
  tests/test_send.py
  tests/test_telegram.py
Labels: enhancement

#130 为 Receipt 添加 MessageId 的转换支持
  nonebot_plugin_saa/adapters/dodo.py
  nonebot_plugin_saa/adapters/feishu.py
  nonebot_plugin_saa/adapters/kaiheila.py
  nonebot_plugin_saa/adapters/onebot_v11.py
  nonebot_plugin_saa/adapters/onebot_v12.py
  nonebot_plugin_saa/adapters/qq.py
  nonebot_plugin_saa/adapters/qqguild.py
  nonebot_plugin_saa/adapters/red.py
  nonebot_plugin_saa/adapters/telegram.py
  nonebot_plugin_saa/registries/receipt.py
  tests/test_dodo.py
  tests/test_feishu.py
  tests/test_kaiheila.py
  tests/test_onebot_v11.py
  tests/test_onebot_v12.py
  tests/test_qq.py
  tests/test_qqguild.py
  tests/test_red.py
  tests/test_telegram.py
Labels: enhancement

#132 放宽AggregatedMessageFactory.__init__的类型约束
  nonebot_plugin_saa/abstract_factories.py
Labels: bug

#137 Ci: Support preview
  .github/actions/setup-node/action.yml
  .github/workflows/test.yml
  .github/workflows/website-deploy.yml
  .github/workflows/website-preview.yml
  yarn.lock
Labels: skip-changelog

#133 完善使用文档
  docs/docs/assets/plugin-only-text.png
  docs/docs/assets/plugin-text-image.png
  docs/docs/usage/01-quickstart.md
  docs/docs/usage/02-message-build.md
  docs/docs/usage/03-send.md
  docs/docs/usage/03-send.mdx
  docs/docs/usage/04-custom.md
  docs/docs/usage/06-config.md
  docs/docusaurus.config.js
  docs/package.json
  docs/src/components/Curtain.tsx
  docs/src/components/DotMark.tsx
  docs/src/css/heimu.css
  docs/tsconfig.json
  pnpm-lock.yaml
Labels: documentation
