Repository MountainDash/nonebot-plugin-send-anything-anywhere, pull requests merged in 2024-02, with the labels that each got.

#146 更新kaiheila适配器版本至0.3.0，修改单测
  nonebot_plugin_saa/adapters/kaiheila.py
  poetry.lock
  pyproject.toml
  tests/test_kaiheila.py
Labels: dependencies

#148 移除 qqguild 适配器
  nonebot_plugin_saa/__init__.py
  nonebot_plugin_saa/adapters/__init__.py
  nonebot_plugin_saa/adapters/qqguild.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_auto_select_qqguild_bot.py
  tests/test_qqguild.py
Labels: Breaking

#149 移除 QQGuild 相关文档
  README.md
  nonebot_plugin_saa/utils/const.py
Labels: documentation
